### ISSUE TITLE
Add additional columns to the Sponsor Portal

### ISSUE THREAD

**Issue by Jumb0Fr4m3** [CiscoDevNet/iPSK-Manager#40] opened 2024-04-26 07:17 UTC
Additional columns for the Admin was created (like description) and that it working like a charm. (in #31)
It would be great if we also could get the possibility to have those extra columns on the sponsor portal.

In other words the request is to get the same functionality regarding the extra columns for the sponsor portal, that the Admin portal already have got.

**Comment by ciesinsn** [comment] 2024-04-27 01:18
@Jumb0Fr4m3 had some unexpected free time and was able to knock this out.  Pushing up to master branch and will close this issue out :)

**Closed** 2024-04-27 01:20 UTC
Labels: enhancement

**Comment by Jumb0Fr4m3** [comment] 2024-04-30 07:46
Thanks.
I am able to do filtering on the fields that are already present, but when entering something in the description filter field, nothing happens.
Also I see that when I check the description under Column Visibility and do a refresh, the description field is gone and I have to check it again. It would be great if my preference could be saved.

**Comment by ciesinsn** [comment] 2024-04-30 13:53
It looks like broke on commit 12f4f5a when the different supporting tools where upgraded.   The issue is the logic that dos the search just returns column 0 for the current column.  I'll have to dig deeper into this one.  I'll make a new issue for it.
